### ISSUE TITLE
Custom emojis no longer working

### ISSUE THREAD

**Issue by hifihedgehog** [gdpelican/retort#54] opened 2020-04-18 19:58 UTC
Related to #52. After the fix was applied to issue #52, custom emojis no longer display correctly. Bear in mind that reactions made prior to the fix still display. Please fix this.

Example of a Retort reaction being made after the fix (not working):
https://forum.farfarawaynews.com/t/star-wars-episode-i-racer-coming-to-ps4-and-switch-in-may/837

Example of a Retort reaction that was already made before the fix (still working):
https://forum.farfarawaynews.com/t/taylor-gray-gives-his-thoughts-on-the-rumored-rebels-sequel/822

**Comment by gdpelican** [comment] 2020-04-19 02:32
Hmm, I'm not able to reproduce this; here's a video of me trying:
https://www.loom.com/share/cb1e61a819044f9a9645ed056e04b1cc

Any additional information about how that faulty reaction came to be?

**Comment by hifihedgehog** [comment] 2020-04-19 05:10
None, I'm afraid but I'll keep looking. Whenever a user attempts to click on the custom icons like you do in the video, the faulty reaction appears.

**Comment by hifihedgehog** [comment] 2020-04-19 05:12
I tried clearing my browser cache and that doesn't seem to fix it. Strangely, your new account has no issues, but my preexisting, admin account does.

**Comment by hifihedgehog** [comment] 2020-04-19 05:16
What's even stranger is used the impersonate function with a cleared browser session of your account and the bug occurs. I tried both Chrome and Edge (Chromium), and neither work.

**Comment by hifihedgehog** [comment] 2020-04-19 05:24
I just tried a new test user on a different device entirely (iOS 13, Safari) with no admin rights and that user is exhibiting the same problem.

**Comment by hifihedgehog** [comment] 2020-04-19 05:57
The only thing that stands out is the custom emoji all have ::[name]:: with double colons, which the built-in emojis don't have.

**Comment by hifihedgehog** [comment] 2020-04-19 06:00
Ah, I found the caveat! Typing in the emoji name, they work! _But_ selecting any of the custom emojis WITHOUT typing anything doesn't work and will apply the double colons.

**Comment by gdpelican** [comment] 2020-04-19 19:44
Huh, very weird. I'll have a look today.

**Comment by gdpelican** [comment] 2020-04-19 20:19
This appears to be a bug in discourse core, which actually looks like it's already been fixed by this commit:
https://github.com/discourse/discourse/commit/cfe510cbcf7c3fa9a9407c17d8eba735a23ecc96

Try updating discourse again and see how you go?

**Closed** 2020-04-19 20:21 UTC
